"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvidor from "@/ThemeProvidor/ThemeProvidor";
import { Moon_Dance, Luckiest_Guy, Caveat } from "next/font/google";

// const inter = Moon_Dance({
//   subsets: ["latin"],
//   variable: "--font-moon-dance",
//   weight: "400",
// });

const inter = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  weight: "700",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <ThemeProvidor>{children}</ThemeProvidor>
      </body>
    </html>
  );
}
